
export const maritalStatuses = [
    "Never married",
    "Widowed",
    "Divorced",
    "Awaiting for divorce"
]

export const citiesMaharastra = [
    "None",
    "Pune",
    "Nagpur",
    "Baramati",
    "Pusad"
]

export const statesIndia = [
    "None",
    "Maharastra",
    "Gujarat",
    "Rajasthan",
    "Haryana",
    "Punjab",
    "Uttarakhand",
    "Uttar Pradesh",
    "Madhya Pradesh",
    "Chattisgarh",
    "Jharkhand",
    "Bihar",
    "West Bengal",
    "Odisha",
    "Sikkim",
    "Himachal Pradesh",
    "Assam",
    "Meghalaya",
    "Arunachal Pradesh",
    "Nagaland",
    "Manipur",
    "Mizoram",
    "Tripura",
    "Karnataka",
    "Tamil Nadu",
    "Andhra Pradesh",
    "Telangana",
    "Kerala",
    "Goa"
]

export const countries = [
    "None",
    "India",
    "Isril",
    "United States",
    "China",
    "Japan",
    "Germany",
    "United Kingdom",
    "France",
    "Russia",
    "Canada",
    "Italy",
    "Brazil",
    "Australia",
    "South Korea",
    "Mexico",
    "Spain",
    "Indonesia",
    "Saudi Arabia",
    "Netherlands",
    "Turkey",
    "Switzerland",
    "Poland",
    "Argentina",
    "Sweden",
    "Norway",
    "Belgium",
    "Ireland",
    "Israel",
    "United Arab Emirates",
    "Thailand",
    "Nigeria",
    "Egypt",
    "Austria",
    "Singapur",
    "Bangladesh",
    "Vietnam",
    "Malaysia",
    "South Africa",
    "Philippines",
    "Denmark",
    "Iran",
    "Pakistan",
    "Hong Kong",
    "Colombia",
    "Romania",
    "Chile",
    "Czech Republic (Czechia)",
    "Finland",
    "Iraq",
    "Portugal",
    "New Zealand",
    "Peru"
]